### ISSUE TITLE
Trolling WEI on agaton(may be other servers)

### ISSUE THREAD

**Issue by TromPT** [Xeio/WanderLost#153] opened 2022-09-29 14:05 UTC
I have to admit while last server downtime i contributed to troll merchants as protest for longest downtime ever.
It was funny to see reported WEI on AGATON 4 different places at the same time with like 40 likes on each.

Yesterday i have saw someone trolling and WEI with 2 likes then 40 negatives on it.
Is there a chance that a report with some positives and high negatives are still counted as false positive on the stats?

Agaton | 09-28 18:30
Agaton | 09-28 09:30
Agaton | 09-28 08:30

**Comment by Xeio** [comment] 2022-09-29 15:08
Usually the problem is there are more positive votes than negative. Several of those instances have 60+ votes, though the sum of the votes comes out to 5-10.

Seems to be a problem on the SA servers more than elsewhere that they like to upvote the trolls, particularly during downtime. :P

**Comment by TromPT** [comment] 2022-09-29 15:15
ive saw may be a clan pushing a fake wei and had like 40 pos but 300 negs, not so long ago same server.
unless downtime that is obvious wei is not there since server is down, that trolling may occur for fun, but most of the time the reports are legit, some mistakes, i made 1 reporting the wrong location trying to be faster but its not common to have a bad report.
most of the people like the page and try to make it good

**Comment by Xeio** [comment] 2022-09-29 15:41
A possibly crazy idea is I could poll the https://www.playlostark.com/en-us/support/server-status page occasionally to check if servers are in marked as in maintenance.

Not sure if I could get that to work super-reliably or not though, and I probably would only poll it every once in a while.

**Comment by TromPT** [comment] 2022-09-29 15:59
problem is not the intended trolling, the problem is the false positives as of yesterday, there were no 3 wei, not even 1

**Comment by Xeio** [comment] 2022-09-29 17:18
Eh, it's the difference between a band-aid and a more reliable fix. I don't really want to need to get into the habit of manually deleting entries when the servers are down. Trying to keep the site as low-maintenance as possible.

**Comment by Flexbar** [comment] 2022-09-30 03:25
"contributed to troll merchants as protest for longest downtime ever."
Could anyone enlighten me why people would like to do this on a fan made noneprofit website? Will this ever hurt AGS or SG?

**Comment by Xeio** [comment] 2022-09-30 03:29
Someone posted this screenshot last month from one of the maintenance then too (for one of the SA servers): https://i.imgur.com/7OtaLl1.png

🤷‍♂️

**Comment by Xeio** [comment] 2022-09-30 19:35
I put in a possible mitigator for this, in theory the site will no longer let you submit while the server status page says a server is in maintenance mode... though won't really be sure it works or not till next maintenance window.

**Closed by Xeio** 2022-09-30 19:35 UTC

**Comment by TromPT** [comment] 2022-10-01 03:34
i was part of this, i guess we never meant to hurt this effort 7th this month

![image](https://user-images.githubusercontent.com/114674399/193385810-3d975d05-dfdf-4400-899e-7cb72d7c068a.png)
