### ISSUE TITLE
notification on Android

### ISSUE THREAD

**Issue by MoGHenry** [Xeio/WanderLost#61] opened 2022-04-25 14:54 UTC
If I close the page, I can't receive any notification. I have to scream on lock and stay on the page to receive notification, even though I enabled the notification premission for Chrome an this web

**Comment by ujellyx** [comment] 2022-04-25 22:12
Same. I'd love to have some possibility for mobile notifications, maybe even via third party notification services (e. g. Pushbullet). Or a straight up Lostmerchant-App.

**Comment by Xeio** [comment] 2022-04-25 22:28
So the biggest trick to push notifications is generally that the server needs to know preferences to know when to push a notification.  So at a minimum this is likely blocked until there are user accounts where settings can be stored. 

Secondary is the "how" which is complicated by what platform/browser is getting the push, since I don't think there is a fully browser-agnostic way to configure service workers (and android/ios are their own monsters). Also I think that may require a paid service to handle the pushes but if have to look into that more.

So possible... but not likely in the near term.

**Comment by marcpancorbo** [comment] 2022-04-29 16:47
> 
You cold try to use firebase, there is not really need to store users as long as you store browser tokens.
I worked on some PWA applications and thats the way to go, the only problem is Safari that actually doesn't allow push notifications

**Comment by Xeio** [comment] 2022-04-29 17:00
If I push every event through Firebase (and have the client can do the filtering), that's probably close to 2 orders of magnitude more events than just pushing the actual things that would notify a particular user. I haven't specifically looked up pricing on this sort of thing before but usually cloud services charge related to number of pushes and amount of data transferred.

**Comment by marcpancorbo** [comment] 2022-04-29 17:05
Checking pricings it says that FCM it's free, check it out, maybe it's a possible solution 
![image](https://user-images.githubusercontent.com/55668102/165990666-b8fc765c-71da-429a-8ea4-fa6ed7a05280.png)

**Comment by Xeio** [comment] 2022-05-04 21:27
Hmmm, testing browser-based push notifications and it seems like they have a fair delay (5-10 minutes in my testing). When we're talking about a 25 minute window, and that it may take a few minutes for people to enter (and upvote) the merchant that may be too slow. Almost certainly would see some notifications get delivered after the merchants have already expired.

Last time I played with an Android app I recall push events being faster (though at that time I was using Azure Message Hub->Firebase). Not sure if it's a browser thing with some default polling interval, or maybe there's some way to tweak that.

**Comment by Xeio** [comment] 2022-05-13 14:15
This is now available via browser notifications, though it's hidden a bit for now (will add a menu item once I'm reasonably sure it's stable).

For now you can navigate to https://lostmerchants.com/PushNotifications directly to set them up. If y'all want to enable/test them and let me know if you see anything odd, otherwise I'll probably un-hide it sometime this weekend and maybe show a message about the new feature.

Might still be nice to get an app at some point, but that's a fair bit easier add now that the push notification processing logic is implemented.

**Comment by Xeio** [comment] 2022-05-13 23:56
Happy coincidence that my server got a Wei card today so I can confirm Wei push works. I had tested it on the test server, but nice to have an actual instance to be sure. 😄 

Nav menu is un-hidden, and I see some subscribers starting to show up, seems like everything is flowing as expected. I'll probably add a pop-up message too for anyone that misses the toolbar having a new link.

Won't be 100% till the volume of notifications increases, but it's ramping up well so far anyway.

**Comment by Xeio** [comment] 2022-05-25 05:49
Semi-experimental version of an Android app is now up https://github.com/Xeio/WanderLost/releases.

It's basically just a fancy skin for push notification settings, though one minor advantage it has over the browser-based ones is there are separate notification channels for Wei vs Rapport items, so they can be configured to use different sounds.

UI is kinda still clunky, but at least the functionality should be there to receive notifications. I'm probably going to run it side-by-side with the Chrome ones on my phone till I confirm everything is coming across.

Also minor caveat is it may not work after a restart since usually there's a separate permission apps need to declare for that (so may be a good idea to manually start the app after needing a restart), I haven't tested it in that regard to see if Firebase messages need that extra step.

**Closed** 2022-08-26 00:51 UTC
