### ISSUE TITLE
[Feature] Wandering ship tracker

### ISSUE THREAD

**Issue by ArutanSipdrae** [Xeio/WanderLost#101] opened 2022-05-21 01:44 UTC
It would be nice to be able to report Luterra/Vernese ship by indicating which channel they are on and the time left

**Comment by Xeio** [comment] 2022-05-22 18:15
Duplicate of #17. Still unsure if I'll do this or not, but probably lower priority in any case.

**Closed by Xeio** 2022-05-22 18:15 UTC
